services:
  bitcoin:
    image: btcpayserver/bitcoin:24.0.1-1
    container_name: bitcoind
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        server=1
        rest=1
        rpcallowip=0.0.0.0/0
        rpcbind=0.0.0.0
        rpcuser=regtest
        rpcpassword=regtest
        rpcport=18443
        debug=1
        logips=1
        logtimemicros=1
        blockmintxfee=0
        deprecatedrpc=signrawtransaction
        listenonion=0
        fallbackfee=0.00001
        txindex=1
        blockfilterindex=1
        peerblockfilters=1
        listen=1

    ports:
      - '18744:18444'
      - '18743:18443'